### ISSUE TITLE
Kernel Panic under macOS 10.12 Sierra

### ISSUE THREAD

**Issue by skyynet** [OpenSprinkler/OpenSprinkler-Updater#3]
Just bought an OpenSprinkler DC (hardware 2.3) and wanted to update firmware 2.1.6(1) to 2.1.6(2). Installation of Updater worked fine. After start it told me I should install the included drivers which I did. The corresponding reboot finished with a kernel panic. I unplugged the OpenSprinkler's USB connection and rebooted. This worked. When I attached the USB cable it immediately crashed with another kernel panic.

Is there and update? If not, which kext do I have to remove?

Report following:

Anonymous UUID:       E833D1D4-2328-FB89-C16A-3F912DFA444B

Sun Oct 23 01:09:11 2016

**\* Panic Report ***
panic(cpu 2 caller 0xffffff8029609f4a): Kernel trap at 0xffffff802954182c, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0xffffff8fffffffa6, CR3: 0x000000002cf19000, CR4: 0x00000000000626e0
RAX: 0xffffff90c534b000, RBX: 0x0000000000000000, RCX: 0xffffffff3acb4f90, RDX: 0xffffff8029ccd5d0
RSP: 0xffffff90c52f3c30, RBP: 0xffffff90c52f3d00, RSI: 0xffffff90c534bdee, RDI: 0xffffff8029c6a0e0
R8:  0xffffff7fac67e728, R9:  0x0000000000000000, R10: 0xffffff8029d20a68, R11: 0xffffff809ce86058
R12: 0xffffff803635e000, R13: 0xffffff8029c6a0e0, R14: 0x0000000000000000, R15: 0xffffff90c534bdee
RFL: 0x0000000000010287, RIP: 0xffffff802954182c, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0xffffff8fffffffa6, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0

Backtrace (CPU 2), Frame : Return Address
0xffffff90c52f38c0 : 0xffffff80294f748c 
0xffffff90c52f3940 : 0xffffff8029609f4a 
0xffffff90c52f3b20 : 0xffffff80294a9743 
0xffffff90c52f3b40 : 0xffffff802954182c 
0xffffff90c52f3d00 : 0xffffff8029a86fe6 
0xffffff90c52f3d20 : 0xffffff7faa03900a 
0xffffff90c52f3d70 : 0xffffff7fa9fc600a 
0xffffff90c52f3d90 : 0xffffff7fa9fcbf9d 
0xffffff90c52f3e10 : 0xffffff8029ac00ba 
0xffffff90c52f3e80 : 0xffffff7fa9fcb8dd 
0xffffff90c52f3ed0 : 0xffffff7fa9fd07e1 
0xffffff90c52f3f10 : 0xffffff7fa9fd053f 
0xffffff90c52f3f30 : 0xffffff8029abd621 
0xffffff90c52f3f80 : 0xffffff8029abcc06 
0xffffff90c52f3fb0 : 0xffffff80294a6af7 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOUSBHostFamily(1.1)[6A671CD8-5527-3A10-8675-1421D158D7A7]@0xffffff7fa9f95000->0xffffff7fa9ffcfff
            dependency: com.apple.driver.AppleBusPowerController(1.0)[DB526B45-1A45-3A81-A0C1-57F826CADEDF]@0xffffff7fa9f88000
         com.apple.iokit.IOUSBFamily(900.4.1)[8F6207EC-608D-373A-B35E-E6578202F58D]@0xffffff7faa005000->0xffffff7faa09dfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[731443D8-78D5-30C8-939A-1ED3E857CA22]@0xffffff7fa9e4a000
            dependency: com.apple.iokit.IOUSBHostFamily(1.1)[6A671CD8-5527-3A10-8675-1421D158D7A7]@0xffffff7fa9f95000

BSD process name corresponding to current thread: kernel_task
Boot args: kext-dev-mode=1

Mac OS version:
16A323

Kernel version:
Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64
Kernel UUID: 622D2470-C34D-31F9-A62B-6AA9A3C6A3CD
Kernel slide:     0x0000000029200000
Kernel text base: 0xffffff8029400000
__HIB  text base: 0xffffff8029300000
System model name: MacBookAir4,2 (Mac-742912EFDBEE19B3)

System uptime in nanoseconds: 10065413540
last loaded kext at 9500755454: com.wch.usbserial   1 (addr 0xffffff7fac67b000, size 36864)
loaded kexts:
com.wch.usbserial   1
com.paragon-software.filesystems.ntfs   359.2.14
com.splashtop.driver.SRXFrameBufferConnector    1.6
com.Cycling74.driver.Soundflower    2
com.splashtop.driver.SRXDisplayCard 1.6
com.Ralink.driver.RT2870USBWirelessDriver   5.0.1
com.elgato.ElgatoThunderboltDockAudioRename 1.0.3
at.obdev.nke.LittleSnitch   4718
com.Elgato.ThunderboltDockChargingSupport   1.0.0
com.apple.driver.AppleOSXWatchdog   1
com.apple.driver.AppleMikeyHIDDriver    127
com.apple.driver.AppleHDAHardwareConfigDriver   276.26
com.apple.driver.AppleHDA   276.26
com.apple.driver.ApplePolicyControl 3.13.60
com.apple.driver.AppleFIVRDriver    4.1.0
com.apple.driver.AppleIntelHD3000Graphics   10.0.2
com.apple.driver.AppleMikeyDriver   276.26
com.apple.driver.AppleUpstreamUserClient    3.6.4
com.apple.driver.AppleThunderboltIP 3.0.8
com.apple.driver.AppleMuxControl    3.13.60
com.apple.driver.AppleLPC   3.1
com.apple.driver.AppleBacklight 170.9.10
com.apple.driver.AppleMCCSControl   1.2.13
com.apple.driver.AppleSMCPDRC   1.0.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport 5.0.0f18
com.apple.driver.AudioAUUC  1.70
com.apple.driver.AppleSMCLMU    208
com.apple.driver.ACPI_SMC_PlatformPlugin    1.0.0
com.apple.driver.pmtelemetry    1
com.apple.iokit.IOUserEthernet  1.0.1
com.apple.iokit.IOBluetoothSerialManager    5.0.0f18
com.apple.Dont_Steal_Mac_OS_X   7.0.0
com.apple.driver.AppleHV    1
com.apple.driver.AppleIntelSlowAdaptiveClocking 4.0.0
com.apple.driver.AppleIntelSNBGraphicsFB    10.0.2
com.apple.iokit.SCSITaskUserClient  394
com.apple.iokit.IOBluetoothUSBDFU   5.0.0f18
com.apple.driver.AppleUSBStorageCoexistentDriver    404.1.1
com.apple.driver.AppleUSBCardReader 404.1.1
com.apple.driver.AppleUSBTCButtons  251
com.apple.driver.AppleUSBTCKeyEventDriver   251
com.apple.driver.AppleUSBTCKeyboard 251
com.apple.driver.CoreStorageFsck    540
com.apple.driver.AppleFileSystemDriver  3.0.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless 1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib 1.0.0
com.apple.BootCache 39
com.apple.filesystems.hfs.kext  366.1.1
com.apple.driver.AppleIntelI210Ethernet 2.3.0
com.apple.iokit.IOAHCIBlockStorage  295.1.1
com.apple.driver.AirPort.Brcm4331   800.20.24
com.apple.driver.AirPort.Brcm4360   1100.37.1a16
com.apple.driver.AppleAHCIPort  326
com.apple.driver.AppleSmartBatteryManager   161.0.0
com.apple.driver.AppleRTC   2.0
com.apple.driver.AppleACPIButtons   5.0
com.apple.driver.AppleHPET  1.8
com.apple.driver.AppleSMBIOS    2.1
com.apple.driver.AppleACPIEC    5.0
com.apple.driver.AppleAPIC  1.7
com.apple.driver.AppleIntelCPUPowerManagementClient 219.0.0
com.apple.nke.applicationfirewall   171
com.apple.security.quarantine   3
com.apple.security.TMSafetyNet  8
com.apple.driver.AppleIntelCPUPowerManagement   219.0.0
com.apple.driver.AppleBluetoothHIDKeyboard  197
com.apple.driver.IOBluetoothHIDDriver   5.0.0f18
com.apple.driver.AppleHIDKeyboard   197
com.apple.driver.DspFuncLib 276.26
com.apple.kext.OSvKernDSPLib    525
com.apple.driver.AppleThunderboltEDMSink    4.1.1
com.apple.driver.AppleHDAController 276.26
com.apple.iokit.IOHDAFamily 276.26
com.apple.driver.AppleSMBusPCI  1.0.14d1
com.apple.driver.AppleGraphicsControl   3.13.60
com.apple.driver.AppleBacklightExpert   1.1.0
com.apple.iokit.IONDRVSupport   2.4.1
com.apple.driver.AppleSMBusController   1.0.14d1
com.apple.iokit.IOBluetoothHostControllerUSBTransport   5.0.0f18
com.apple.iokit.IOBluetoothHostControllerTransport  5.0.0f18
com.apple.driver.IOPlatformPluginLegacy 1.0.0
com.apple.driver.IOPlatformPluginFamily 6.0.0d8
com.apple.iokit.IOSurface   152
com.apple.iokit.IOSerialFamily  11
com.apple.iokit.IOBluetoothFamily   5.0.0f18
com.apple.driver.AppleSMC   3.1.9
com.apple.iokit.IOSlowAdaptiveClockingFamily    1.0.0
com.apple.iokit.IOGraphicsFamily    2.4.1
com.apple.iokit.IOUSBMassStorageClass   4.0.4
com.apple.iokit.IOSCSIBlockCommandsDevice   394
com.apple.iokit.IOUSBMassStorageDriver  131.1.1
com.apple.iokit.IOSCSIArchitectureModelFamily   394
com.apple.driver.AppleUSBMultitouch 258
com.apple.driver.usb.IOUSBHostHIDDevice 1.1
com.apple.driver.AppleUSBAudio  305.62
com.apple.iokit.IOAudioFamily   205.11
com.apple.vecLib.kext   1.2.0
com.apple.driver.AppleThunderboltDPInAdapter    4.5.3
com.apple.driver.AppleThunderboltDPOutAdapter   4.5.3
com.apple.driver.AppleThunderboltDPAdapterFamily    4.5.3
com.apple.driver.AppleThunderboltPCIUpAdapter   2.0.3
com.apple.driver.AppleThunderboltPCIDownAdapter 2.0.3
com.apple.driver.CoreStorage    540
com.apple.filesystems.hfs.encodings.kext    1
com.apple.driver.usb.cdc    5.0.0
com.apple.driver.usb.networking 5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice    1.1
com.apple.driver.usb.AppleUSBHub    1.1
com.apple.driver.AppleXsanScheme    3
com.apple.driver.usb.AppleUSBXHCIPCI    1.1
com.apple.driver.usb.AppleUSBXHCI   1.1
com.apple.iokit.IOEthernetAVBController 1.0.3b4
com.apple.driver.AppleUSBMergeNub   900.4.1
com.apple.driver.AppleThunderboltNHI    4.1.3
com.apple.iokit.IOThunderboltFamily 6.2.1
com.apple.iokit.IO80211Family   1200.12.2
com.apple.driver.mDNSOffloadUserClient  1.0.1b8
com.apple.iokit.IONetworkingFamily  3.2
com.apple.driver.corecapture    1.0.4
com.apple.driver.usb.AppleUSBHostPacketFilter   1.0
com.apple.iokit.IOAHCIFamily    288
com.apple.iokit.IOUSBFamily 900.4.1
com.apple.driver.usb.AppleUSBEHCIPCI    1.1
com.apple.driver.usb.AppleUSBUHCIPCI    1.1
com.apple.driver.usb.AppleUSBUHCI   1.1
com.apple.driver.usb.AppleUSBEHCI   1.1
com.apple.iokit.IOUSBHostFamily 1.1
com.apple.driver.AppleUSBHostMergeProperties    1.1
com.apple.driver.AppleEFINVRAM  2.1
com.apple.driver.AppleEFIRuntime    2.0
com.apple.driver.AppleBusPowerController    1.0
com.apple.iokit.IOHIDFamily 2.0.0
com.apple.iokit.IOSMBusFamily   1.1
com.apple.security.sandbox  300.0
com.apple.kext.AppleMatch   1.0.0d1
com.apple.driver.AppleKeyStore  2
com.apple.driver.AppleMobileFileIntegrity   1.0.5
com.apple.driver.AppleCredentialManager 1.0
com.apple.driver.DiskImages 444
com.apple.iokit.IOStorageFamily 2.1
com.apple.iokit.IOReportFamily  31
com.apple.driver.AppleFDEKeyStore   28.30
com.apple.driver.AppleACPIPlatform  5.0
com.apple.iokit.IOPCIFamily 2.9
com.apple.iokit.IOACPIFamily    1.4
com.apple.kec.pthread   1
com.apple.kec.corecrypto    1.0
com.apple.kec.Libm  1
Model: MacBookAir4,2, BootROM MBA41.0077.B14, 2 processors, Intel Core i5, 1,7 GHz, 4 GB, SMC 1.73f66
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1333 MHz, 0x80CE, 0x4D34373142353737334448302D4348392020
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1333 MHz, 0x80CE, 0x4D34373142353737334448302D4348392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xE9), Broadcom BCM43xx 1.0 (5.106.98.100.24)
Bluetooth: Version 5.0.0f18, 3 services, 27 devices, 1 incoming serial ports
Network Service: Thunderbolt Ethernet Slot 2, Ethernet, en8
PCI Card: ethernet, Ethernet Controller, Thunderbolt@131,0,0
PCI Card: pci1b73,1100, USB eXtensible Host Controller, Thunderbolt@132,0,0
Serial ATA Device: OWC Aura Pro 6G SSD, 480,1 GB
USB Device: USB 2.0 Bus
USB Device: FaceTime Camera (Built-in)
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: WiFi
USB Device: Card Reader
USB Device: USB 3.0 Bus
USB Device: USB3.0 Hub
USB Device: USB3.0 Hub
USB Device: USB audio CODEC
USB Device: USB2.0 Hub
USB Device: Jabra PRO 9460
USB Device: Vendor-Specific Device
USB Device: USB2.0 Hub
Thunderbolt Bus: MacBook Air, Apple Inc., 8.1
Thunderbolt Device: Thunderbolt Dock, Elgato Systems, 1, 30.1

**Comment by rayshobby** [comment]
I am pretty sure this is a driver related issue. I googled 'ch340g mac sierra' and found some solutions, for example:
https://tzapu.com/ch340-ch341-serial-adapters-macos-sierra/
there is a link on that way that points to an updated driver that works with sierra (and also how to remove the existing driver). We will update the driver link shortly (but I need to do some test to make sure it also works with the current El Capitan)

**Comment by skyynet** [comment]
Thanks,
This worked for my under Sierra. The docs in the mentioned drivers claim they'll work for macOS 10.9+ so it should be safe to exchange them with the faulty ones currently bundled with the updater.
